# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - 'main'
    - 'dev'

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    cd $(System.DefaultWorkingDirectory)/azure-aks-usermgmt-webapp-demo/..
    ls -a
    pwd 
      # "Current working directory: $(Agent.BuildDirectory)"
    cat "Test.Trade.ReMoS.AssuranceService.API.sln"
  displayName: 'Run a multi-line script'
  continueOnError: true
- script: |
    echo Add other tasks to build, test, and deploy your project.
    cat "./Test.Trade.ReMoS.AssuranceService.API.sln"
  displayName: 'Run a multi-line script'  
